### ISSUE TITLE
Support for Zero Averaging (Cadence, Watts)

### ISSUE THREAD

**Issue by HlisTilen** [firefly-cpp/tcxread#4]
- [✅] - avg_cadence_zero_avg_on (Filter out zero - current implementation) 
- [❌] - avg_cadence_zero_avg_off (add)
- [✅] - avg_watts_zero_avg_on (Filter out zero - current implementation)
- [❌] - avg_watts_zero_avg_off (add)

**Comment by firefly-cpp** [comment]
Thanks, fixed now.
